### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Coinsyy** [raiguard/EditorExtensions#142]
### Description

![image](https://github.com/raiguard/EditorExtensions/assets/138596631/fcf81630-af37-451e-b102-c1462741fff3)

**Comment by raiguard** [comment]
This has been fixed on the Crowdin side. I have re-enabled Crowdin QA checks, so this hopefully won't happen again.

**Comment by wvffle** [comment]
@raiguard That's still happening to me on the version 2.1.5 but for a line 141 which seems to be commented: 

https://github.com/raiguard/EditorExtensions/blob/master/locale/pl/EditorExtensions.cfg#L141 

![image](https://github.com/raiguard/EditorExtensions/assets/13330620/41048468-f672-4350-9a5a-2d580c71350d)

**Comment by raiguard** [comment]
FFS crowdin.
